- alias: kiki
  name: Kiki Füßel
  web: https://twitter.com/merenbey/status/1196919880680914944
  tenure_start: 11/2019
  role: Mood Regulator
  avatar: bio-kiki.jpg
  address: Helmholtz Institute for Functional Marine Biodiversity (HIFMB), Im Technologiepark 5, 26129 Oldenburg, Germany
  bio: "I am an environmental scientist and a passionate anthropologist who has mastered the use of somatosensory, olfactory, and gustatory systems. If you need to schedule a meeting with me for my services, feel free to reach my personal assistant, Meren."
  affiliations:
    - title: Therapy Dog

- alias: juniper
  name: Juniper Veseli
  tenure_start: 11/2024
  role: Food Safety Officer
  avatar: bio-juniper.jpg
  address: Helmholtz Institute for Functional Marine Biodiversity (HIFMB), Im Technologiepark 5, 26129 Oldenburg, Germany
  bio: "When I'm not investigating biofilms on food and kitchen counters, I am a social scientist studying the efficacy of different human manipulation techniques. To participate in my research study on cuddling, please contact my study coordinator, Iva."
  affiliations:
    - title: Cat

- alias: princess
  name: Princess Peach Trigodet
  tenure_start: 11/2024
  role: Princess
  avatar: bio-princess.jpg
  address: Helmholtz Institute for Functional Marine Biodiversity (HIFMB), Im Technologiepark 5, 26129 Oldenburg, Germany
  bio: "In addition to ruling over my domain (and my sister, Juniper), I dabble in materials research by investigating the durability of materials to dental stress. My specialty is cardboard and silicone. If you must be graced by my presence, you may arrange an audience through Florian."
  affiliations:
    - title: Her Majesty
